import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "@/Context/Cart";
import { CategoryProvider } from "@/Context/Categories";
import UIProvider from "@/Context/UI";
import ProductFormProvider from "@/Context/ProductForm";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { ToastProvider } from "@/Context/toast";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} scroll-smooth `}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <SessionProvider>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <CategoryProvider>
              <ProductFormProvider>
                <UIProvider>
                  <ToastProvider>
                    <Toaster />
                    <CartProvider>{children}</CartProvider>
                  </ToastProvider>
                </UIProvider>
              </ProductFormProvider>
            </CategoryProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
